apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-magnus-miniapp
spec:
  build:
    secrets:
        - SECRET_1
        - SECRET_2
  environments:
    - name: dev
      build:
        from: main
    - name: nodeploymentenv
    - name: featureenv
      build:
        from: feature/*
    - name: nonconfigbranchenv
      build:
        from: nonconfigbranch
  components:
    - name: server
      ingressConfiguration:
        - stickysessions
      variables:
        public_port: 8080
      ports:
        - name: http
          port: 8080
      publicPort: http
    - name: redis-submodule
      src: submodule-example
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379
    # - name: dnsmasq
    #   src: dnsmasq
    #   ports:
    #    - name: dns
    #      port: 53
      