apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-magnus-miniapp
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: server
      runAsNonRoot: true
      ports:
        - name: http
          port: 8080
      publicPort: http
      environmentConfig:
        - environment: dev
          replicas: 2
      ingressConfiguration:
        - leastconnectedlb
