apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-magnus-miniapp
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: featureenv
      build:
        from: feature/*
    - name: nonconfigbranchenv
      build:
        from: nonconfigbranch
  components:
    - name: server
      variables:
        public_port: 8080
      ports:
        - name: http
          port: 8080
      publicPort: http
    - name: delete-me
      variables:
        public_port: 8081
      ports:
        - name: http2
          port: 8081
#       environmentConfig:
#         - environment: dev
#           replicas: 2
#       ingressConfiguration:
#         - leastconnectedlb
    # - name: gpucomponent
    #   runAsNonRoot: true
    #   ports:
    #     - name: http2
    #       port: 8080
    #   node:
    #     gpu: nvidia-v100
    #     gpuCount: 2
    #   environmentConfig:
    #     - environment: dev
    #       replicas: 2
